name: Windows build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
        platform:
          - amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup MinGW and NSIS and curl
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install mingw
          scoop install nsis
          
      - name: Setup NSIS PATH_strlen special patch
        run: |
          Expand-Archive -Path "nsis-3.10-strlen_8192.zip" -DestinationPath "nsis-strlen"
          Remove-Item  ~\scoop\apps\nsis\current\Bin\
          Remove-Item  ~\scoop\apps\nsis\current\Stubs\
          Remove-Item  ~\scoop\apps\nsis\current\makensis.exe
          Move-Item -Path nsis-strlen/* -Destination ~\scoop\apps\nsis\current -Force
            
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.22'
        
      - name: configure
        run: |
          cmake -S . -B build  -G "MinGW Makefiles"
          
      - name: build
        run: |
          cmake --build build --config Release
          cd build
          cpack -C Release
          cd ..
          
      - name: Upload windows build to GH release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}     
          file: build/rockpaperscissor-${{ github.ref_name }}-win64.exe
          asset_name: RockPaperScissor-${{ github.ref_name }}-${{ matrix.os }}.exe
          prerelease: true
