name: Windows build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
        platform:
          - amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
        
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.22'
          
      - name: Install NSIS
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install nsis
          
      - name: Print NSIS version
        run: makensis -VERSION
        
      - name: configure
        run: |
          cmake -S . -B build  -G "MinGW Makefiles"
          
      - name: build
        run: |
          cmake --build build --config Release
          cpack
          
      - name: Upload windows build to GH release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}     
          file: build/rockpaperscissor-${{ github.ref_name }}-win64.exe
          asset_name: RockPaperScissor-${{ github.ref_name }}-${{ matrix.os }}.exe
          prerelease: true
