name: ubuntu build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        platform:
          - amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.22'
        
      - name: build and package
        run: |
          make pkgdeb

      - name: report build dir
        run: |
          cd build
          ls
          cd ..
      - name: Upload unbuntu build to GH release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}     
          file: build/RockPaperScissor-${{ github.ref_name }}-amd64.deb
          asset_name: RockPaperScissor-${{ github.ref_name }}-${{ matrix.os }}.deb
          prerelease: true
