name: Windows build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
        platform:
          - amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install NSIS
        uses: repolevedavaj/install-nsis@v1.0.2
        
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup MinGW
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install mingw
          
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.22'
        
      - name: configure
        run: |
          cmake -S . -B build  -G "MinGW Makefiles" -DCPACK_LINUX_GEN_NAME=NSIS
          
      - name: build
        run: |
          cmake --build build --config Release -DCPACK_LINUX_GEN_NAME=NSIS
          cd build
          cpack -C Release
          cd ..
          
      - name: Upload windows build to GH release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}     
          file: build/rpsg-${{ github.ref_name }}-win64.exe
          asset_name: RockPaperScissor-${{ github.ref_name }}-${{ matrix.os }}.exe
          prerelease: true
